from __future__ import annotations

from importlib import util as importlib_util
from pathlib import Path
from types import ModuleType
from typing import Any


def _load_guard() -> ModuleType:
    repo_root = Path(__file__).resolve().parent.parent
    module_path = repo_root / "tools" / "renovate_guard.py"
    spec = importlib_util.spec_from_file_location("_tools_renovate_guard", module_path)
    assert spec is not None and spec.loader is not None
    module = importlib_util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


guard = _load_guard()

COMPILED_LOCK = "requirements/constraints.txt"
HEADER_WITH_ALL_INPUTS = (
    "#\n"
    "# This file is autogenerated by pip-compile with Python 3.12\n"
    "# by the following command:\n"
    "#\n"
    "#    pip-compile --all-extras --output-file=requirements/constraints.txt "
    "--strip-extras pyproject.toml requirements/dev-compile.in requirements/overrides.in\n"
)
HEADER_WITHOUT_OVERRIDES = HEADER_WITH_ALL_INPUTS.replace(
    " requirements/overrides.in", ""
)

EXPECTED_WARNINGS = (
    {"level": 40, "msg": "GitHub token is required for some dependencies"},
    {"level": 40, "msg": "Package file requirements/overrides.in has no deps"},
    {"level": 30, "msg": "Failed to find a version for requires-python"},
    {"level": 30, "msg": "Cannot find build-system requirement"},
)


def _report(
    entries: list[dict[str, Any]], manager: str = "pip-compile"
) -> dict[str, Any]:
    return {
        "problems": [],
        "repositories": {
            "local": {
                "problems": [],
                "packageFiles": {manager: entries},
            },
        },
    }


def _owned(*sources: str) -> list[dict[str, Any]]:
    return [
        {"packageFile": source, "lockFiles": [COMPILED_LOCK], "deps": []}
        for source in sources
    ]


def test_accepts_every_source_extracted_as_an_owned_association() -> None:
    report = _report(
        _owned(
            "pyproject.toml", "requirements/dev-compile.in", "requirements/overrides.in"
        )
    )

    assert guard.check_ownership(report, HEADER_WITH_ALL_INPUTS) == []


def test_accepts_a_comments_only_override_proved_by_the_generated_header() -> None:
    report = _report(_owned("pyproject.toml", "requirements/dev-compile.in"))

    assert guard.check_ownership(report, HEADER_WITH_ALL_INPUTS) == []


def test_rejects_an_override_absent_from_both_the_report_and_the_header() -> None:
    report = _report(_owned("pyproject.toml", "requirements/dev-compile.in"))

    findings = guard.check_ownership(report, HEADER_WITHOUT_OVERRIDES)

    assert len(findings) == 1
    assert "requirements/overrides.in" in findings[0]


def test_ignores_unknown_report_fields() -> None:
    report = _report(
        _owned(
            "pyproject.toml", "requirements/dev-compile.in", "requirements/overrides.in"
        )
    )
    report["libYearsWithStatus"] = {"managerStatus": {}}
    report["repositories"]["local"]["branches"] = []
    for entry in report["repositories"]["local"]["packageFiles"]["pip-compile"]:
        entry["extractedConstraints"] = {"python": "==3.12"}

    assert guard.check_ownership(report, HEADER_WITH_ALL_INPUTS) == []


def test_tolerates_the_documented_local_extraction_warnings() -> None:
    report = _report(_owned("pyproject.toml", "requirements/dev-compile.in"))
    report["problems"] = list(EXPECTED_WARNINGS)
    report["repositories"]["local"]["problems"] = list(EXPECTED_WARNINGS)

    assert guard.check_ownership(report, HEADER_WITH_ALL_INPUTS) == []


def test_reports_every_missing_association_together() -> None:
    findings = guard.check_ownership(_report([]), HEADER_WITHOUT_OVERRIDES)

    assert len(findings) == 3
    joined = "\n".join(findings)
    assert "pyproject.toml" in joined
    assert "requirements/dev-compile.in" in joined
    assert "requirements/overrides.in" in joined


def test_rejects_a_source_owned_by_a_manager_other_than_pip_compile() -> None:
    report = _report(
        _owned("pyproject.toml", "requirements/dev-compile.in"), manager="pep621"
    )

    findings = guard.check_ownership(report, HEADER_WITH_ALL_INPUTS)

    assert len(findings) == 2


def test_rejects_a_source_extracted_without_the_compiled_lock_attached() -> None:
    report = _report(
        [
            {"packageFile": "pyproject.toml", "lockFiles": [], "deps": []},
            {
                "packageFile": "requirements/dev-compile.in",
                "lockFiles": [COMPILED_LOCK],
                "deps": [],
            },
        ]
    )

    findings = guard.check_ownership(report, HEADER_WITH_ALL_INPUTS)

    assert len(findings) == 1
    assert "pyproject.toml" in findings[0]


def test_reports_malformed_required_fields_alongside_missing_associations() -> None:
    report = _report(
        [
            {"packageFile": "pyproject.toml", "lockFiles": COMPILED_LOCK},
            {"lockFiles": [COMPILED_LOCK]},
        ]
    )

    findings = guard.check_ownership(report, HEADER_WITHOUT_OVERRIDES)

    joined = "\n".join(findings)
    assert "malformed" in joined
    assert "pyproject.toml" in joined
    assert "requirements/dev-compile.in" in joined
    assert "requirements/overrides.in" in joined


def test_the_generated_header_stops_at_the_first_pinned_requirement() -> None:
    lock_text = (
        HEADER_WITHOUT_OVERRIDES
        + "pip-tools==7.6.1\n    # via -r requirements/overrides.in\n"
    )

    assert "requirements/overrides.in" not in guard.generated_header(lock_text)


def test_rejects_an_override_named_only_by_a_via_annotation() -> None:
    report = _report(_owned("pyproject.toml", "requirements/dev-compile.in"))
    lock_text = (
        HEADER_WITHOUT_OVERRIDES
        + "pip-tools==7.6.1\n    # via -r requirements/overrides.in\n"
    )

    findings = guard.check_ownership(report, guard.generated_header(lock_text))

    assert len(findings) == 1
    assert "requirements/overrides.in" in findings[0]


def test_reports_a_malformed_report_root() -> None:
    findings = guard.check_ownership([], HEADER_WITH_ALL_INPUTS)

    assert "malformed" in findings[0]
    assert len(findings) == 1 + len(("pyproject.toml", "requirements/dev-compile.in"))


def test_reports_a_malformed_package_files_section() -> None:
    report = _report([])
    report["repositories"]["local"]["packageFiles"] = "pip-compile"

    findings = guard.check_ownership(report, HEADER_WITH_ALL_INPUTS)

    assert any("malformed" in finding for finding in findings)


def test_main_exits_zero_and_stays_quiet_on_a_satisfied_contract(
    tmp_path: Path, capsys: Any
) -> None:
    report_file = tmp_path / "report.json"
    report_file.write_text(
        __import__("json").dumps(
            _report(_owned("pyproject.toml", "requirements/dev-compile.in"))
        )
    )
    lock_file = tmp_path / "constraints.txt"
    lock_file.write_text(HEADER_WITH_ALL_INPUTS)

    exit_code = guard.main(["--report", str(report_file), "--lock", str(lock_file)])

    assert exit_code == 0
    assert capsys.readouterr().err == ""


def test_main_exits_non_zero_and_prints_every_finding(
    tmp_path: Path, capsys: Any
) -> None:
    report_file = tmp_path / "report.json"
    report_file.write_text(__import__("json").dumps(_report([])))
    lock_file = tmp_path / "constraints.txt"
    lock_file.write_text(HEADER_WITHOUT_OVERRIDES)

    exit_code = guard.main(["--report", str(report_file), "--lock", str(lock_file)])

    stderr = capsys.readouterr().err
    assert exit_code == 1
    assert "pyproject.toml" in stderr
    assert "requirements/dev-compile.in" in stderr
    assert "requirements/overrides.in" in stderr


def test_main_reports_an_unreadable_extraction_report(
    tmp_path: Path, capsys: Any
) -> None:
    report_file = tmp_path / "report.json"
    report_file.write_text("{not json")
    lock_file = tmp_path / "constraints.txt"
    lock_file.write_text(HEADER_WITH_ALL_INPUTS)

    exit_code = guard.main(["--report", str(report_file), "--lock", str(lock_file)])

    assert exit_code == 1
    assert "extraction report" in capsys.readouterr().err
