name: Changelog Updating

"on":
  release:
    types: [released]

jobs:
  update_changelog:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36  # v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8
        with:
          add-paths: |
            CHANGELOG.md
          commit-message: "docs(changelog): update changelog"
          title: "docs(changelog): update changelog"
          body: Update changelog to reflect release changes
          branch: docs-changelog_update
          delete-branch: true
